#include "config_io.h"

#include <QFile>
#include <QSaveFile>
#include <QTemporaryFile>

#include <cmath>
#include <iomanip>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <variant>

#include "../../FlexASIOUtil/shell.h"

namespace flexasio_gui {

	namespace {

		constexpr auto configFileName = L"FlexASIO.toml";

		std::string QuoteTomlString(const std::string& value) {
			std::string result = "\"";
			constexpr char hex[] = "0123456789ABCDEF";
			for (const unsigned char c : value) {
				switch (c) {
				case '\\': result += "\\\\"; break;
				case '"': result += "\\\""; break;
				case '\n': result += "\\n"; break;
				case '\t': result += "\\t"; break;
				case '\r': result += "\\r"; break;
				default:
					if (c < 0x20 || c == 0x7f) {
						result += "\\u00";
						result += hex[(c >> 4) & 0xf];
						result += hex[c & 0xf];
					}
					else result += char(c);
				}
			}
			result += "\"";
			return result;
		}

		// tinytoml keeps integer and floating-point literals distinct. FlexASIO reads
		// suggestedLatencySeconds as a double, so serializing 0.0 as `0` makes an
		// otherwise well-formed file fail configuration validation.
		std::string FormatTomlFloat(double value) {
			if (!std::isfinite(value)) throw std::runtime_error("TOML cannot represent a non-finite latency value");
			std::ostringstream result;
			result << std::showpoint << std::setprecision(std::numeric_limits<double>::max_digits10) << value;
			return result.str();
		}

		void WriteDevice(std::ostream& out, const flexasio::Config::Device& device) {
			std::visit([&](const auto& value) {
				using T = std::decay_t<decltype(value)>;
				if constexpr (std::is_same_v<T, flexasio::Config::DefaultDevice>) {
					// Omitted: absence of both `device` and `deviceRegex` means "use the default device".
				}
				else if constexpr (std::is_same_v<T, flexasio::Config::NoDevice>) {
					out << "device = \"\"\n";
				}
				else if constexpr (std::is_same_v<T, std::string>) {
					out << "device = " << QuoteTomlString(value) << "\n";
				}
				else if constexpr (std::is_same_v<T, flexasio::Config::DeviceRegex>) {
					out << "deviceRegex = " << QuoteTomlString(value.getString()) << "\n";
				}
			}, device);
		}

		void WriteStream(std::ostream& out, const flexasio::Config::Stream& stream) {
			WriteDevice(out, stream.device);
			if (stream.channels.has_value()) out << "channels = " << *stream.channels << "\n";
			if (stream.sampleType.has_value()) out << "sampleType = " << QuoteTomlString(*stream.sampleType) << "\n";
			if (stream.suggestedLatencySeconds.has_value()) out << "suggestedLatencySeconds = " << FormatTomlFloat(*stream.suggestedLatencySeconds) << "\n";
			out << "wasapiExclusiveMode = " << (stream.wasapiExclusiveMode ? "true" : "false") << "\n";
			out << "wasapiAutoConvert = " << (stream.wasapiAutoConvert ? "true" : "false") << "\n";
			out << "wasapiExplicitSampleFormat = " << (stream.wasapiExplicitSampleFormat ? "true" : "false") << "\n";
		}

	}

	std::filesystem::path GetConfigPath() {
		return std::filesystem::path(flexasio::GetUserDirectory()) / configFileName;
	}

	flexasio::Config LoadConfig() {
		return flexasio::LoadConfigFile(GetConfigPath());
	}

	void ValidateConfig(const flexasio::Config& config) {
		if (config.bufferSizeSamples.has_value() && (*config.bufferSizeSamples < 8 || *config.bufferSizeSamples > 1024))
			throw std::runtime_error("Buffer size must be between 8 and 1024 samples");
		for (const auto* stream : {&config.input, &config.output}) {
			if (stream->channels.has_value() && (*stream->channels < 1 || *stream->channels > 256))
				throw std::runtime_error("Channel count must be between 1 and 256");
			if (stream->suggestedLatencySeconds.has_value() && (!std::isfinite(*stream->suggestedLatencySeconds) || *stream->suggestedLatencySeconds < 0 || *stream->suggestedLatencySeconds > 3600))
				throw std::runtime_error("Suggested latency must be a finite value between 0 and 3600 seconds");
			if (stream->sampleType.has_value() && *stream->sampleType != "Float32" && *stream->sampleType != "Int32" && *stream->sampleType != "Int24" && *stream->sampleType != "Int16")
				throw std::runtime_error("Sample type must be Float32, Int32, Int24, or Int16");
		}
	}

	std::string SerializeConfig(const flexasio::Config& config) {
		ValidateConfig(config);
		std::ostringstream out;
		out << std::setprecision(9);
		out << "# Generated by FlexASIO GUI Tester\n\n";
		if (config.backend.has_value()) out << "backend = " << QuoteTomlString(*config.backend) << "\n";
		if (config.bufferSizeSamples.has_value()) out << "bufferSizeSamples = " << *config.bufferSizeSamples << "\n";

		out << "\n[input]\n";
		WriteStream(out, config.input);
		out << "\n[output]\n";
		WriteStream(out, config.output);

		return out.str();
	}

	void SaveConfigToPath(const flexasio::Config& config, const std::filesystem::path& path) {
		const auto content = SerializeConfig(config);
		if (content.size() > 1024 * 1024) throw std::runtime_error("Generated configuration exceeds the 1 MiB safety limit");

		QTemporaryFile validationFile;
		validationFile.setAutoRemove(true);
		if (!validationFile.open()) throw std::runtime_error("Unable to create temporary configuration validation file");
		if (validationFile.write(content.data(), qint64(content.size())) != qint64(content.size()))
			throw std::runtime_error("Unable to write temporary configuration validation file");
		validationFile.flush();
		validationFile.close();
		try { flexasio::LoadConfigFile(std::filesystem::path(validationFile.fileName().toStdWString())); }
		catch (...) { std::throw_with_nested(std::runtime_error("Generated TOML was rejected by FlexASIO's configuration loader")); }

		const QString target = QString::fromStdWString(path.wstring());
		const QString backup = target + ".bak";
		if (QFile::exists(target)) {
			try {
				flexasio::LoadConfigFile(path);
				QFile source(target);
				if (!source.open(QIODevice::ReadOnly)) throw std::runtime_error("Unable to read existing configuration for backup");
				QSaveFile backupFile(backup);
				if (!backupFile.open(QIODevice::WriteOnly)) throw std::runtime_error("Unable to open configuration backup");
				const auto previous = source.readAll();
				if (backupFile.write(previous) != previous.size() || !backupFile.commit()) throw std::runtime_error("Unable to save configuration backup");
			}
			catch (const std::exception&) {
				// Do not promote malformed prior content into a known-good backup.
			}
		}

		QSaveFile file(target);
		if (!file.open(QIODevice::WriteOnly)) throw std::runtime_error("Unable to open FlexASIO.toml for atomic writing");
		if (file.write(content.data(), qint64(content.size())) != qint64(content.size()) || !file.commit())
			throw std::runtime_error("Unable to atomically replace FlexASIO.toml");
	}

	void SaveConfig(const flexasio::Config& config) {
		SaveConfigToPath(config, GetConfigPath());
	}

}
