#include "config_io.h"

#include <fstream>
#include <iomanip>
#include <sstream>
#include <stdexcept>
#include <variant>

#include "../../FlexASIOUtil/shell.h"

namespace flexasio_gui {

	namespace {

		constexpr auto configFileName = L"FlexASIO.toml";

		std::string QuoteTomlString(const std::string& value) {
			std::string result = "\"";
			for (const char c : value) {
				switch (c) {
				case '\\': result += "\\\\"; break;
				case '"': result += "\\\""; break;
				case '\n': result += "\\n"; break;
				case '\t': result += "\\t"; break;
				case '\r': result += "\\r"; break;
				default: result += c;
				}
			}
			result += "\"";
			return result;
		}

		void WriteDevice(std::ostream& out, const flexasio::Config::Device& device) {
			std::visit([&](const auto& value) {
				using T = std::decay_t<decltype(value)>;
				if constexpr (std::is_same_v<T, flexasio::Config::DefaultDevice>) {
					// Omitted: absence of both `device` and `deviceRegex` means "use the default device".
				}
				else if constexpr (std::is_same_v<T, flexasio::Config::NoDevice>) {
					out << "device = \"\"\n";
				}
				else if constexpr (std::is_same_v<T, std::string>) {
					out << "device = " << QuoteTomlString(value) << "\n";
				}
				else if constexpr (std::is_same_v<T, flexasio::Config::DeviceRegex>) {
					out << "deviceRegex = " << QuoteTomlString(value.getString()) << "\n";
				}
			}, device);
		}

		void WriteStream(std::ostream& out, const flexasio::Config::Stream& stream) {
			WriteDevice(out, stream.device);
			if (stream.channels.has_value()) out << "channels = " << *stream.channels << "\n";
			if (stream.sampleType.has_value()) out << "sampleType = " << QuoteTomlString(*stream.sampleType) << "\n";
			if (stream.suggestedLatencySeconds.has_value()) out << "suggestedLatencySeconds = " << *stream.suggestedLatencySeconds << "\n";
			out << "wasapiExclusiveMode = " << (stream.wasapiExclusiveMode ? "true" : "false") << "\n";
			out << "wasapiAutoConvert = " << (stream.wasapiAutoConvert ? "true" : "false") << "\n";
			out << "wasapiExplicitSampleFormat = " << (stream.wasapiExplicitSampleFormat ? "true" : "false") << "\n";
		}

	}

	std::filesystem::path GetConfigPath() {
		return std::filesystem::path(flexasio::GetUserDirectory()) / configFileName;
	}

	flexasio::Config LoadConfig() {
		flexasio::ConfigLoader loader;
		return loader.Initial();
	}

	void SaveConfig(const flexasio::Config& config) {
		std::ostringstream out;
		out << std::setprecision(9);
		out << "# Generated by FlexASIO GUI Tester\n\n";
		if (config.backend.has_value()) out << "backend = " << QuoteTomlString(*config.backend) << "\n";
		if (config.bufferSizeSamples.has_value()) out << "bufferSizeSamples = " << *config.bufferSizeSamples << "\n";

		out << "\n[input]\n";
		WriteStream(out, config.input);
		out << "\n[output]\n";
		WriteStream(out, config.output);

		const auto path = GetConfigPath();
		std::ofstream file(path, std::ios::binary | std::ios::trunc);
		if (!file) throw std::runtime_error("Unable to open FlexASIO.toml for writing");
		const auto content = out.str();
		file.write(content.data(), std::streamsize(content.size()));
		if (!file) throw std::runtime_error("Unable to write FlexASIO.toml");
	}

}
